# Site settings
title:          Walk
description:    "SJ Lee blog"
baseurl:        "/"
url:            "https://lsj0410.github.io"

# Google Analytics
google_analytics: UA-238384915-1

# Author
author:
  name:         SJ Lee
  url:          "https://sites.google.com/snu.ac.kr/seungjulee"
  email:        ""

# Build settings
markdown:       kramdown
highlighter:    rouge
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale
