# Site settings
title:          Walk
description:    "SJ Lee blog"
baseurl:        "/"
url:            "https://lsj0410.github.io"

# Google Analytics
google_analytics: UA-238384915-1

# Author
author:
  name:         SJ Lee
  url:          "https://sites.google.com/snu.ac.kr/seungjulee"
  email:        "seungj11@snu.ac.kr"

# Build settings
markdown:       GFM
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale

footer-links:
  email: seungj11@snu.ac.kr
  facebook:
  flickr:
  github: lsj0410
  googleplus: # anything in your profile username that comes after plus.google.com/
  instagram: 
  linkedin: seungju-l-35ba851a4
  pinterest:
  rss: # just type anything here for a working RSS icon
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  tumblr: # https://<username>.tumblr.com
  twitter:
  youtube: # channel/<your_long_string> or user/<user-name>
